### ISSUE TITLE
Support of the jedi-stack at Orion

### ISSUE THREAD

**Issue by flampouris** [JCSDA/jedi-stack#102]
The jedi modules at Orion as described [here](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/developer/jedi_environment/modules.html#orion) are not built with parallel NetCDF and cause at least all the SOCA apps using NCO to fail.

**Comment by flampouris** [comment]
@aerorahul thank you very much!

**Comment by guillaumevernieres** [comment]
Thanks @aerorahul . It fixes the issue for GODAS, I'll let @jkbk2004 or @flampouris test before closing.
It does not fix the issue with mom6 failing, but that can be addressed later.

**Comment by flampouris** [comment]
tested.-
