### ISSUE TITLE
Upgrade hdf5 library to at least version 1.12.0 for new ioda interface

### ISSUE THREAD

**Issue by srherbener** [JCSDA/jedi-stack#117]
We will need hdf5 1.12.0 (or newer) for the new ioda interface.

**Comment by rhoneyager** [comment]
Since this still conflicts with h5py, I am fine with 1.10. We lose a feature or two, but these probably won't be used in the release.

**Comment by srherbener** [comment]
I believe that using a version of hdf5 less than 1.12.0 will disable the select mode where the indexes of each dimension are specified for the HH backend. This should still work for the ObsStore backend which is really where we need that feature, so I think it should be okay to stay on hdf5 1.10 for a while.

On the other hand, doesn't h5py install the underlying hdf5 library that it is compatible with so in theory shouldn't we able to use hdf5 1.12.0 for non-Python applications while Python uses a different version?

**Comment by srherbener** [comment]
What's a good test for checking if the conflict exists? I am able to start up ptyhon3 and import h5py successfully with hdf5 1.12.0 built and installed by jedi-stack. This includes having the path to the hdf5 1.12.0 libraries on LD_LIBRARY_PATH. I take it that I need to run something beyond the import to see the problem. Thanks!

**Comment by mmiesch** [comment]
My own experience is that hdf5 can be a bit delicate on different platforms (especially HPC platforms) and different models (how they do parallel io, if at all).  So, if it's not really needed immediately, I would lean toward not upgrading a few months before the release - we've been using 1.10.6 for a while and nobody seems to have a problem with it.  But, if it adds important functionality then we should upgrade and just test as much as we can.

**Comment by srherbener** [comment]
I'm okay with staying on 1.10.6 for now. I should have what I need in ioda-engines for the release.

Does this mean that @markjolah's PR in jedi-stack (JCSDA/jedi-stack#120) should back off from 1.12.0 to 1.10.6?

**Comment by srherbener** [comment]
I found this article from the HDF group:

https://www.hdfgroup.org/wp-content/uploads/2020/03/Webinar-Moving-applications-from-1.10-to-HDF5-1.12-release-.pdf

They mention that a file created by hdf5 1.12.0 may not be readable by an application built with 1.10.* (which includes h5py). @rhoneyager, is this the conflict that you mentioned?

**Comment by rhoneyager** [comment]
> I found this article from the HDF group:
> 
> https://www.hdfgroup.org/wp-content/uploads/2020/03/Webinar-Moving-applications-from-1.10-to-HDF5-1.12-release-.pdf
> 
> They mention that a file created by hdf5 1.12.0 may not be readable by an application built with 1.10.* (which includes h5py). @rhoneyager, is this the conflict that you mentioned?

Nope. Looks like the conflict that I was noting has since been resolved - h5py explicitly binds to the HDF5 v1.8 API, which is always available. [link](https://github.com/h5py/h5py/blob/21bc91f14c7d50cf9af67a6161bffe270a9150f3/setup_build.py#L41)

So, no objections code-wise.
