### ISSUE TITLE
szip is no longer used in building MPI

### ISSUE THREAD

**Issue by aerorahul** [JCSDA/jedi-stack#121]
It appears that someone, somewhere along the way removed the dependency of building MPI with `szip` support.

If you look at [build_mpi.sh](https://github.com/JCSDA/jedi-stack/blob/develop/buildscripts/libs/build_mpi.sh), it no longer loads `szip` module.  If that is ok (and I think it is), then `setup_modules.sh` can be greatly simplified and the building of MPI (or COMPILER) can be included in `build_stack.sh`.

Besides, `setup_modules.sh` is doing more than setting up just modules.  I think we should break it into 2 separate scripts;  setup_modules script and build compiler and/or mpi script.

**Comment by aerorahul** [comment]
@mmiesch @markjolah 
Is this still valid for your uses? 

If so, I wish to move the building of MPI from `setup_modules.sh` to `build_stack.sh`
I have a working prototype on my mac.

**Comment by aerorahul** [comment]
@mmiesch @markjolah 
Can I remove `szip` building from `setup_modules.sh`?

**Comment by markjolah** [comment]
Yes, but you may want to leave the actual build script availible because HDF5 can use szip as a compression backend.  I'm not sure if we're using that option or not in the stack build, but I do build HDF5 that way as part of my base system.

**Comment by aerorahul** [comment]
Indeed.  Not removing the `build_szip.sh` from the repo.  Just removing the call to it from `setup_modules.sh`.

Aside note; are we/anyone using szip for compression? The UFS model uses zlib for compression.  zlib is faster for compression, szip is efficient at zipping/unzipping.  Someone did a comparison. FWIW.

**Comment by mmiesch** [comment]
Yes - szip can still be built with `build_stack.sh` and I believe we have it configured for hdf5 to use it.  But, it can be removed from `setup_modules.sh`
