### ISSUE TITLE
C++14 support for JEDI

### ISSUE THREAD

**Issue by markjolah** [JCSDA/jedi-stack#125]
Since the merge of [oops # 763](https://github.com/JCSDA/oops/pull/763) which uses `std::make_unique`, a C++14 feature, we were getting build failures for intel-based jedi-stack modules systems on many(all) HPC environments.  See e.g., [fv3-bundle # 31](https://github.com/JCSDA/fv3-bundle/issues/31)

The issue is that the intel compilers do not provide `libstdc++`, so it must piggyback on a GCC provided `libstdc++`.  Whatever gcc version is found by `which gcc` is going to be the one picked by Intel by default and this GCC version will then determine the c++ standards compatibility.   For all HPC installs of jedi-stack we are using the system's provided GCC which for `s4`, `orion`, `cheyenne`, `discover` (and probably also `hera`) is `gcc-4.8.5` which lacks c++14 support.  We require `>=gcc-5` to support c++14.  For machines with a more modern GCC available as a loadable module (orion, cheyenne, discover), we can load the GCC module as part of the Intel module.  Then we would use the methods of PR #120 which allows setting CXXFLAGS in the compiler-wrapper module and propagate the `-gcc-name=` flag to the build scripts which will then allow the correct `libstdc++` to be used.  For S4 which doesn't have a more modern GCC, we would need to build at least the `libstdc++` component of `gcc-9.3.0` which is the latest Intel-compatible GCC.  

As this is a rather complex addition to the stack and it will continue to block any C++ modernization for all of JEDI packages until addressed, I thought I would link in the relevant parties here for discussion: @mmiesch @rickgrubin @danholdaway @aerorahul @ytremolet

**Comment by markjolah** [comment]
One comment is that we actually don't need the `-gcc-name=` flag to build any of the stack packages themselves.  Only the `core/jedi-intel` module needs to append to `CXXFLAGS` so that when loaded the correct GCC is used for Intel, and then inside the bundle `CXXFLAGS` will take effect to enable C++14 support.

**Comment by mmiesch** [comment]
Yes - we should work this out but it will take some preparation.  On some systems, there may be a conflict - one may not be allowed to load a gnu compiler module and then an intel compiler module.    Even if this is possible, we will probably have to rebuild the entire stack to make it compatible with the jedi bundles.  So, I agree to disable this for now and then look into it and make sure this strategy will work on all systems.

**Comment by markjolah** [comment]
One more simplification.  We don't even need to fully load the gnu modules.  We just need to add the path-to-new-gcc to the `PATH` variable.  As long as `which gcc` evaluates to something newer than gcc-5, we should be OK.  We don't want any of the other "effects" of loading the gcc module, just the path to gcc executable is enough.

**Comment by mmiesch** [comment]
So S4 is ready for testing this out.  The default gcc is 4.8 but 8.3 is available in `/opt/gcc/8.3/bin`.  So, I tried building with Intel 19 and the `-gxx-name=/opt/gcc/8.3/bin/g++` flag added to CXX.  My first try failed in the fckit compilation.  So, I unloaded my eckit module and tried building eckit with the bundle but fckit still fails - Does this approach lead to an incompatibility between the version of glibcxx that is used for jedi and the version that was used to build intel mpi?

```
[ 40%] Linking Fortran executable fckit_test_mpi
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const'
../../../lib/libfckit.so: undefined reference to `VTT for std::__cxx11::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_erase(unsigned long, unsigned long)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_not_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace_aux(unsigned long, unsigned long, unsigned long, char)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::basic_istream<char, std::char_traits<char> >& std::operator>><char, std::char_traits<char>, std::allocator<char> >(std::basic_istream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&)@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::rfind(char, unsigned long) const@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::operator<< <char, std::char_traits<char>, std::allocator<char> >(std::basic_ostream<char, std::char_traits<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
../../../lib/libfckit.so: undefined reference to `std::__throw_out_of_range_fmt(char const*, ...)'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `VTT for std::__cxx11::basic_istringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_append(char const*, unsigned long)'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::reserve(unsigned long)'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::resize(unsigned long, char)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char, unsigned long) const@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_last_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_mutate(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `VTT for std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_replace(unsigned long, unsigned long, char const*, unsigned long)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >::_M_sync(char*, unsigned long, unsigned long)@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find_first_of(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit.so: undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::find(char const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'
../../../lib/libfckit.so: undefined reference to `__cxa_throw_bad_array_new_length'
/data/users/mmiesch/jedi/ufo-bundle/build/lib/libeckit_mpi.so: undefined reference to `vtable for std::__cxx11::basic_stringbuf<char, std::char_traits<char>, std::allocator<char> >@GLIBCXX_3.4.21'
make[2]: *** [fckit/src/tests/fckit_test_mpi] Error 1
make[1]: *** [fckit/src/tests/CMakeFiles/fckit_test_mpi.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by mmiesch** [comment]
How do you tell ecbuild to build eckit with cxx 14 support?  It's getting my `-gxx-name=/opt/gcc/8.3/bin/g++` flag but it's also using `-std=gnu++11`

**Comment by mmiesch** [comment]
i have an update.  I think for the C++-14 functionality on the HPC systems we just need the header filess.  So, instead of specifying `-cxx-name` as described above (because we do not have the ability to re-compile intel mpi with this), I just added this flag to the S4 toolchain:
```
set( CMAKE_CXX_FLAGS "-I/opt/gcc/8.3/include" CACHE STRING "Use gcc 8.3 headers for Intel" FORCE )
```
With this I wass able to successfully build and test the `feature/json_schema_generation` branch of oops.  However, I'm not 100% sure that this brranch requires c++-14 so I can't rule out the possibility that this include directory is just being ignored.  So, then ii tried to build ioda-engines to check but that build failed on what I think is an unrelated topic - I'm using version 1.10.5 of hdf5, which I think is not sufficient.

So - I think the include flag is the way to go but I still need too confirm that.

**Comment by markjolah** [comment]
I am not so sure.  Won't you still need to link against `libstdc++.so`?  If you link to the system's gcc-4.8.5 `libstdc++.so` using new headers I'm surprised there were not linking errors as they are not ABI compatible.  See: [libstdc++ abi compatability](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html)

**Comment by markjolah** [comment]
@mmiesch Currently c++14 support is controlled as a "compile feature" of the "oops" target.  It marks this `PUBLIC` so it is propogated to all dependencies, thus causing those dependencies to also have support.  To change the setting see: [`oops/src/CMakeLists.txt`](https://github.com/JCSDA/oops/blob/b00cc20290067f7edbd6c57fb0bd697c890d2d5e/src/CMakeLists.txt#L430)
```
target_compile_features( ${PROJECT_NAME} PUBLIC cxx_std_11 )
```

**Comment by markjolah** [comment]
@mmiesch (Sorry, I'm reading and replying to your post's in reverse order. )  It looks like the first post is the classic C++ ABI mismatch problem I was warning about.  Unfortunately this means that all C++ programs compiled as part of jedi-stack that will be linked to any JEDI package will also need to have the newer C++ ABI enabled when they are compiled.  This is just `eckit` and `atlas`.  We don't use the C++ part of NetCDF, and the boost libraries we use are just the headers.  Hopefully that is all.

**Comment by mmiesch** [comment]
Update - I take back what I said - the include is not working.  I tried reverting oops#768, adding back in a `make_unique` and it is not building for the reasons you suggest.    We can rebuild the stack.  But, what I worry about is the failure above in `fckit_test_mpi`.  To me, this implies that the installation of intel mpi was done with links to the gcc 4.8 headers & libraries.  So, even if we rebuild the stack, intel mpi may still be using the incompatible headers.

**Comment by markjolah** [comment]
@mmiesch The above error is an error in eckit C++ ABI, not fckit or mpi.  I don't expect you would need to recompile the mpi distribution, as it doesn't use C++.  Just eckit and atlas.

**Comment by mmiesch** [comment]
That is wil recompiling eckit and atlas.  I get the above error even when I unload my eckit module and build eckit and atlas as part of the bundle.

**Comment by markjolah** [comment]
You want to check for which CXXABIs are involved in the failing linker line.  Look at which libraries are getting added in, which version of `libstdc++.so` is going to be linked, and then look through each library and make sure they were linked against the correct CXXABI (or older)

All libraries involved in a link must have been built against a `libstdc++.so` with the same or older CXXABI as is used in the `libstdc++.so` on the linker line. 

Some useful commands:
```
$ nm libname.so | grep CXXABI
$ readelf -V libname.so
```

**Comment by mmiesch** [comment]
Thanks for the tip.  Looks like both `libeckit_mpi` and `/opt/gcc/8.3/lib` are using CXXABI 1.3:

```
[mmiesch@s4-submit build]$ nm lib/libeckit_mpi.so | grep CXXABI
                 U __cxa_allocate_exception@@CXXABI_1.3
                 U __cxa_bad_cast@@CXXABI_1.3
                 U __cxa_begin_catch@@CXXABI_1.3
                 U __cxa_call_unexpected@@CXXABI_1.3
                 U __cxa_end_catch@@CXXABI_1.3
                 U __cxa_guard_abort@@CXXABI_1.3
                 U __cxa_guard_acquire@@CXXABI_1.3
                 U __cxa_guard_release@@CXXABI_1.3
                 U __cxa_pure_virtual@@CXXABI_1.3
                 U __cxa_rethrow@@CXXABI_1.3
                 U __cxa_throw@@CXXABI_1.3
                 U __dynamic_cast@@CXXABI_1.3
                 U __gxx_personality_v0@@CXXABI_1.3
                 U _ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3
                 U _ZTVN10__cxxabiv120__si_class_type_infoE@@CXXABI_1.3
                 U _ZTVN10__cxxabiv121__vmi_class_type_infoE@@CXXABI_1.3
[mmiesch@s4-submit build]$ nm /opt/gcc/8.3/lib/libstdc++.so | grep CXXABI
00000000 A CXXABI_1.3
00000000 A CXXABI_1.3.1
00000000 A CXXABI_1.3.10
00000000 A CXXABI_1.3.11
00000000 A CXXABI_1.3.2
00000000 A CXXABI_1.3.3
00000000 A CXXABI_1.3.4
00000000 A CXXABI_1.3.5
00000000 A CXXABI_1.3.6
00000000 A CXXABI_1.3.7
00000000 A CXXABI_1.3.8
00000000 A CXXABI_1.3.9
00000000 A CXXABI_FLOAT128
00000000 A CXXABI_TM_1
```

And, nothing is using CXXABI in `$I_MPI_ROOT/intel64/lib/`

**Comment by mmiesch** [comment]
But ldd shows the error
```
[mmiesch@s4-submit lib]$ ldd libeckit_mpi.so 
./libeckit_mpi.so: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./libeckit_mpi.so)
```

**Comment by markjolah** [comment]
It's slightly more complex as those are the minimal ABI versions necessary for that symbol.  Also, as I guess you found out there are the `GLIBCXX` ABI symbols.  You can look up what you need on the [GCC ABI Compatibility page](https://gcc.gnu.org/onlinedocs/libstdc++/manual/abi.html).  You look for the largest values of `CXXABI` and `GLIBCXX` in the `.so` you want to link against.  Then lookup the oldest gcc version that has both symbols and you have your minimum required version.  E.g., you see maximum `CXXABI=1.3`, which corresponds to this line:
```
GCC 3.4.1: GLIBCXX_3.4.1, CXXABI_1.3
```
So you need at least `gcc-3.4.1` to find all the symbols needed for the `CXXABI`.  Now you also require at least `GLIBCXX= 3.4.21` (which can be checked with another nm grep command).  That constraint is given by line:
```
GCC 5.1.0: GLIBCXX_3.4.21, CXXABI_1.3.9
```
Therefore you will require a `libstdc++.so` from `>=gcc-5.1.0` to compile against the `libeckit.so` you have.  The error is saying that you are still linking against the `libstdc++.so` from the root prefix which is going to still be `gcc-4.8.5` which does not meet ABI comparability because it is missing symbols.

**Comment by markjolah** [comment]
Note that this can only happen if `eckit` was built with the newer `gcc-8.3.0`.  As the older `gcc-4.8.5` could never produce such symbols which were added in later versions.

**Comment by rhoneyager** [comment]
You might also want to take a look at this: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html, particularly the ```_GLIBCXX_USE_CXX11_ABI``` macro.

**Comment by srherbener** [comment]
When I try to build ioda-engines standalone on S4, I get this from mpiicc (Intel 19.0.5) compiler:

```
/data/users/sherbener/projects/ioda-engines/Examples/C/03-VariablesIntro.c(184): error: type name is not allowed
  	for (size_t i = 0; i < 4; ++i)
  	     ^

/data/users/sherbener/projects/ioda-engines/Examples/C/03-VariablesIntro.c(184): error: expected a ";"
  	for (size_t i = 0; i < 4; ++i)
  	            ^

/data/users/sherbener/projects/ioda-engines/Examples/C/03-VariablesIntro.c(184): error: identifier "i" is undefined
  	for (size_t i = 0; i < 4; ++i)
  	                   ^

compilation aborted for /data/users/sherbener/projects/ioda-engines/Examples/C/03-VariablesIntro.c (code 2)
```

The source code that it's complaining about is:

```
183         // Compare each string, up to 20 chars. This size is bigger than the input strings.
184         for (size_t i = 0; i < 4; ++i)
185                 if (strncmp(strings[i], str_list->strings[i], 20) != 0) doErr;
```

Not sure what is wrong. It's legal to declare the for loop iteration variable in the loop, correct? 

Here are the modules I have loaded:

```
[sherbener@s4-submit build]$ module list

Currently Loaded Modules:
  1) miniconda/3.7-base   8) jedi-impi/19.0.5      15) bufrlib/master
  2) license_intel/S4     9) udunits/2.2.26        16) nccmp/1.8.6.5
  3) impi/19.0.5         10) hdf5/1.10.5           17) ecbuild/jcsda-3.3.2.jcsda2
  4) intel/19.0.5        11) pnetcdf/1.11.2        18) eckit/jcsda-1.11.6.jcsda1
  5) jedi-intel/19.0.5   12) netcdf/4.7.0          19) jedi/intel19-impi
  6) szip/2.1.1          13) boost-headers/1.68.0
  7) zlib/1.2.11         14) eigen/3.3.5
```

Do I have the correct versions? Intel 19.0.5?

Any idea what is wrong? Thanks!

The hdf5 1.10.5 version for ioda-engines question sounds familiar. There are #ifdef's in the code so it should compile if the hdf5 version is less than 1.12 (a feature that we eventually need is shut off however). I seem to recall that it worked okay with hdf5 1.10.6 so the 1.10.5 version might be too old.

**Comment by mmiesch** [comment]
Yes - those look like the correct modules.  What if you use `std::size_t`?  Worth a try, though it would be annoying to have to replace this everywhere.  One should have to do a `using namespace std` but again, worth a try.

**Comment by rhoneyager** [comment]
@srherbener, @mmiesch That file is an example using the C interface, not C++. Separate issue. File a bug in ioda-engines and I'll take a look.

**Comment by srherbener** [comment]
@rhoneyager, I submitted the issue in ioda-engines. Thanks for your help with this.

**Comment by mmiesch** [comment]
Ok, this is solved on S4.   It was a problem with the availability of the gcc headers & libraries on the compute nodes vs the s4-submit node.  And, I also got it working on Discover.  

Some changes may be needed for this to work with other users.  I was working with my own beta-testing modules.   Now that it's working I need to do a little more testing to see how I need to modify the main modules so others can use it too.  

I'll start to work with Cheyenne now.  I need to update the modules there anyway to support the latest jedi-stack, including hdf5 1.12.

**Comment by mmiesch** [comment]
I'll work on Cheyenne next

**Comment by markjolah** [comment]
@mmiesch The C++14 aspect of the new modules appears to work great on S4.  Only problem encounterd is that we will need to merge #137 which will fix the bufrlib module, which is currenly broken because it is installing to <prefix>/lib64 but the module file list `lib` when it sets all the paths.  I'm addressing this for CMake packages by adding `-DCMAKE_INSTALL_LIBDIR=lib` as a cmake option.  This will force the package to use `lib` and then the modulefile will also use `lib`.

**Comment by rhoneyager** [comment]
Continuing work on Hera today. Should be testable by this evening.
