### ISSUE TITLE
Finalize jedi-stack for release

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#133]
We need to settle on a jedi-stack configuration that will be compatible with the release.  This means finalizing the versions of all packages specified in `build_stack.sh` and tagging the resulting version of jedi-stack.

This will be the stack version that we put in the containers and in the HPC modules.  We can also include it in the release notes.   We should decide on this well before the release so we have time to generate the containers and modules that will be used for testing the release.  So, a clear deadline for completing this task is before the testing code sprint on Sept 21.

The estimate here is just to talk about when we're ready to finalize the list and create the tag.  We can also define separate tasks for building the tagged stack in HPC modules on all systems and in the development, application, and tutorial containers.

**Comment by rickgrubin** [comment]
To keep the conversation going, this is what the develop branch currently uses for component versions:

```
cmake 3.17.2
udunits 2.2.26
jpeg 9.1.0
zlib 1.2.11
png 1.6.35
zip 2.1.1
lapack 3.7.0
boost 1.68.0 headers-only
eigen 3.3.5
bufrlib master
ecbuild jcsda 3.3.2.jcsda2
cgal 5.0.2


# These must be rebuilt for each MPI implementation
hdf5 1.10.6
pnetcdf 1.12.1
netcdf 4.7.3 4.5.2 4.3.0
nccmp 1.8.6.5
eckit jcsda 1.11.6.jcsda1
fckit jcsda 0.7.0.jcsda1
atlas jcsda 0.20.2.jcsda1
odb 0.18.1.r2
odc jcsda 1.0.3


# Optional Extensions to the JEDI Stack

# MPI-independent
jasper 1.900.1
armadillo 1.900.1
xerces 3.1.4
nceplibs fv3
tkdirr 4.3.5
pyjedi
pybind11 2.5.0

# These must be rebuilt for each MPI implementation
gptl 8.0.3
nco 4.7.9
pio 2.5.0
fftw 3.3.8
boost 1.68.0
esmf 8_0_1
baselibs 5.2.2
pdtoolkit 3.25.1
tau2 3.25.1
```

At a minimum, I believe that `cmake`, `HDF5` (blocker) and `boost` have newer versions that work within the stack.

There are a fair number of feature and bugfix branches that require being addressed as well.

**Comment by rickgrubin** [comment]
Added the `GSL lite header-only` package as a blocker, for the same reason that `HDF5 v1.12.0` is a blocker.

**Comment by mmiesch** [comment]
Thanks @rickgrubin - several of us have been testing with @markjolah 's https://github.com/JCSDA/jedi-stack/pull/120 PR, which has package updates - along with a lot of other things!  I think that has has all the critical updates you mentioned, along with some others.  I think so far so good but we can use that as a starting point and then see if we have any problems.

**Comment by shlyaeva** [comment]
I'm copying question from @wsmigaj here. The proposed dependency would allow to validate yaml files against Schema.

> Do I understand correctly that once we have the whole config tree refactored as Parameters, we'd see the full path to the missing parameter (something like Mandatory parameter 'model/f' not found?)

Yes, that's correct.

Note that the message you've seen comes from the Parameters code in oops itself, not from the JSON schema-based validator (because the JSON validation libraries are probably not installed on your machine yet). The Parameters code can detect the lack of mandatory parameters, but it wouldn't be able to detect misspellings of optional parameters -- only the JSON schema-based validator is able to do that. Do you think it would be possible to add a JSON validation library to the JEDI stack in the near future? https://github.com/JCSDA/oops/issues/784 compares the libraries that I think could do the job -- perhaps we could settle on one of them? (The implementation in #787 uses the first of these libraries, _JSON Schema Validator for Modern C++_, but this could be changed.)

_Originally posted by @wsmigaj in https://github.com/JCSDA/oops/pull/842#issuecomment-686405205_

**Comment by mmiesch** [comment]
Yes - good point - I remember testing @wsmigaj 's feature/parameter_enhancements branch of oops on a few HPC systems and getting the warning that the schema library wasn't found (I forget the name).  Is there something we need to add to the required stack?

**Comment by wsmigaj** [comment]
> Yes - good point - I remember testing @wsmigaj 's feature/parameter_enhancements branch of oops on a few HPC systems and getting the warning that the schema library wasn't found (I forget the name). Is there something we need to add to the required stack?

It would be great if the libraries needed for validation could be added to the JEDI stack (although my intention is to keep validation an optional feature, i.e. it should always be possible to build the code without these libraries). The libraries I'm currently using are [JSON Schema Validator for Modern C++](https://github.com/pboettch/json-schema-validator) and [JSON for Modern C++](https://github.com/nlohmann/json), although as discussed in JCSDA/oops#784 there are some alternatives.

**Comment by wsmigaj** [comment]
@mmiesch Does the above make sense -- can these libraries be added to the stack? Can I help with this in any way?

**Comment by mmiesch** [comment]
Thanks @wsmigaj - yes, it makes sense.  The next step would be to pick one and add it to the stack.  Do you want to go with the first one you mentioned, https://github.com/pboettch/json-schema-validator?  By "add it to the stack" this would mean writing a [build script](https://github.com/JCSDA/jedi-stack/tree/develop/buildscripts/libs) and a [modulefile](https://github.com/JCSDA/jedi-stack/tree/develop/modulefiles) and adding it to the build.  This is straightforward - I can take care of it but I probably won't get to it before my PTO next week.  Or, if you would like to have a go at it, there are instructions in the [README file](https://github.com/JCSDA/jedi-stack/blob/develop/README.md)

**Comment by wsmigaj** [comment]
Thanks @mmiesch -- I'll have a go at it tomorrow.

**Comment by mmiesch** [comment]
Thanks @wsmigaj - I believe it's compiler-independent, right?  So, you can use eigen as a template - just copy these files and edit them accordingly:
https://github.com/JCSDA/jedi-stack/blob/develop/buildscripts/libs/build_eigen.sh
https://github.com/JCSDA/jedi-stack/blob/develop/modulefiles/core/eigen/eigen.lua

**Comment by wsmigaj** [comment]
Thanks for the tip! Yes, I was planning to use either Eigen or gsl-lite as a template.

**Comment by rhoneyager** [comment]
I am preparing a list of packages needed for a deployment of UFO, eventually for WCOSS: [link](https://docs.google.com/spreadsheets/d/1Q1qTqrAKVZH-CV-ht8b7RyAq2ewxP7HaVtIH_un9s2w). Will discuss at today's JEDI1 meeting.
