### ISSUE TITLE
PIO Support for MPAS required on S4, Orion

### ISSUE THREAD

**Issue by markjolah** [JCSDA/jedi-stack#147]
I'm almost complete with the new MPAS CMake, and trying to build on different systems.  On S4, we are missing the PIO library which is a required dependency.   I haven't checked orion yet, but I suppose @rickgrubin is still working on that update so maybe there is time to include it.

I'd like to be able to build the MPAS model on as many platforms as possible as a comparison for performance testing between models on different hardware, so if we can make sure `PIO` and `PnetCDF` are default included for all the Modules/Container builds, I think the mpas-bundle should be portable to all the jedi-stack based systems.

**Comment by mmiesch** [comment]
Thanks @markjolah - sounds good.  I just added it to the `jedi/intel-impi` module on S4.

Note that at the request of the MPAS group, I have been building PIO in debug mode.  So, you'll see this indicated in the module name of `pio/2.5.1-debug`.  I think this solved some problems they were having with gnu/openmpi.  They never did get mpas to run on Cheyenne with the intel modules so I don't know if that's a gnu-specific thing.  And, this doesn't help with the benchmarking you're doing.  

Do you want to continue to use the debug build for pio or should we add a release module too?  I adapted the module names in such a way that we could have both release and debug co-exist and have the option of using one or the other.

**Comment by mmiesch** [comment]
Actually, I take it back - I just installed a release version on S4 so now that's the default: `pio/2.5.1`.  If that gives you problems or if you want a more controlled comparison with Cheyenne you can swap that out for `pio/2.5.1-debug`

**Comment by markjolah** [comment]
Can we also maybe get PIO support on discover?

**Comment by markjolah** [comment]
Confirmed PIO and PnetCDF are working on S4.  For orion I am using `export JEDI_OPT=/work/noaa/da/grubin/opt.beta/modules/`.  It looks like PIO exists for just the `jedi/intel-impi` modules also it is missing from the overall `modulefiles/core/jedi/intel-impi/2020.lua` file.

**Comment by markjolah** [comment]
@rickgrubin I've been testing and I'm about 99% sure we are OK with the current way PIO is built (static library).  It looks like we are always building with `-fPIC` which is all that is necessary to get it working with a shared executable.  It's working on Cheyenne and S4, and I will try Orion again a bit later, but I haven't had a compile problem with the current way we build PIO yet.

**Comment by rickgrubin** [comment]
@markjolah -- `GNU` modules built on **orion**:

```
export JEDI_OPT=/work/noaa/da/grubin/opt/modules
module use $JEDI_OPT/modulefiles/core
module load jedi/gnu-openmpi
```

This will load `GNU v8.3.0` compiler-built modules.

`GNU v10.2.0` compilers are now installed on **orion**; very few system-related modules are built with this suite. In particular, `openmpi-4.0.2` is not, and some stack modules will not build against `openmpi` modules built with `v8.3.0`. I've filed a service request for this issue.

**Comment by mmiesch** [comment]
> Can we also maybe get PIO support on discover?

I just added PIO to the `jedi/intel-impi` and `jedi/gnu-impi` stacks on Discover.  It's not in the baselibs module - let me know if you need it there.
