### ISSUE TITLE
nccmp on S4 needs to be rebuilt against new NetCDF

### ISSUE THREAD

**Issue by markjolah** [JCSDA/jedi-stack#154]
I'm getting the following error on s4 running nccmp from jedi/intel-impi modules.
```
$ which nccmp
/data/users/mmiesch/modules/intel-19.0.5/impi-19.0.5/nccmp/1.8.7.0/bin/nccmp

$ nccmp
nccmp: error while loading shared libraries: libnetcdf.so.15: cannot open shared object file: No such file or directory
```
This is looking for the wrong library because NetCDF is now producing `libnetcdf.so.18`, so probably a rebuild is all that is needed.

**Comment by mmiesch** [comment]
Ok - should be fixed.

**Comment by markjolah** [comment]
Thanks for the fast update!
