### ISSUE TITLE
Find LAPACK, BLAS, and MKL

### ISSUE THREAD

**Issue by ytremolet** [JCSDA/jedi-stack#16]
@mmiesch commented on [Wed May 15 2019](https://github.com/JCSDA/oops/issues/250)

Set up Cmake/ecbuild to find mkl lapack if it exists as the first option

---

@ytremolet commented on [Tue May 21 2019](https://github.com/JCSDA/oops/issues/250#issuecomment-494446201)

Same with MPI.

---

@ytremolet commented on [Tue May 21 2019](https://github.com/JCSDA/oops/issues/250#issuecomment-494450368)

Issue moved to [JCSDA/jedi-stack #15](https://github.com/JCSDA/jedi-stack/issues/15) via [**ZenHub**](https://www.zenhub.com/)

**Comment by markjolah** [comment]
Merging in issues with FindMKL.cmake which will need to coordinate with FindLAPACK.cmake and FindBLAS.cmake.  This issue will become the central point for LAPACK/BLAS/MKL related CMake problems.

**Comment by markjolah** [comment]
Splitting out the note from @ytremolet on 05/21 to address problems with FindMPI.cmake into it's own issue: [JCSDA/jedi-stack#20](https://github.com/JCSDA/jedi-stack/issues/20)

**Comment by markjolah** [comment]
Closed by [oops  # 474](https://github.com/JCSDA/oops/pull/474)
