### ISSUE TITLE
Modules on Discover

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#161]
I'm opening this as an issue so we can communicate about it more readily.

The problem is that first the intel compilers and now the gnu compilers are failing on jedi builds with a message like this:

```bash
/discover/nobackup/mmiesch/jedi/ufo-bundle/ufo-bundle/ufo/src/ufo/ufo_geovals_mod.F90(955): error #7013: This module file was not generated by any release of this compiler.   [NETCDF]
use netcdf
```

This only happens for ufo (in ufo-bundle - maybe also fv3 and soca - I don't know).  If you build oops and saber alone then they build fine and all tests pass, even though they have some identical statements.  I believe I have traced the problem to this module:

```
python/GEOSpyD/Min4.8.3_py3.8
```

We load this as part of the jedi modules in order to have access to python 3.  But, this module also links it its own versions of hdf5 and netcdf that are confusing the ecbuild compilation of ufo.  

I was able to compile ufo-bundle by unloading this module.  But, the problem is not solved because we need python 3 for all the tests to pass - for example, the scripts that get data from AWS S3.

So, I asked support if there is a way to access python3 apart from the GEOSpyD modules.

I'm assigning a number of Discover users just to keep track of updates to this issue.

**Comment by travissluka** [comment]
ah, now it makes sense why I haven't seen this problem....
We explicitly load `cdo` and that python module (was jedi using a different python module by default at one point? that's the only reason I can think of that I was explicitly loading that module) and having realized that the python module conflicts with netcdf, we unload python and cdo before doing a build. It seems that so long as it is unloaded at build time things still work at runtime if that module is loaded. Given that, what would happen if the python module was loaded before netcdf? Or is there some other way we can force ecbuild to use the netcdf from the netcdf module even with the python module loaded?

**Comment by mmiesch** [comment]
I have been loading the python module before netcdf - this seemed sufficient for oops and saber but for some reason it was still confusing ufo.

At the suggestion of the sys admins, I just installed miniconda here:
```
/discover/swdev/jcsda/modules/miniconda3
```

And, I just defined a new module called `jedi-python` that adds that bin directory to your path.  Or, you could put this in your `bashrc` if you always want to run from a miniconda virtual env:
```
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/discover/swdev/jcsda/modules/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/discover/swdev/jcsda/modules/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/discover/swdev/jcsda/modules/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/discover/swdev/jcsda/modules/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<
```

EIther way, this gives you access to python 3.8 without the extra baggage.  I'm testing it now trying to build ufo-bundle with intel

**Comment by danholdaway** [comment]
Thanks @mmiesch, this seems like a straightforward approach and prevents us getting entangled in the GMAO python installs, which obviously aren't that fixed.

**Comment by mmiesch** [comment]
Ok - this seems to have solved the problem for me.  I just build ufo-bundle.  Now testing.

Please give it a try when you get a chance.  You don't have to do anything different - just load either `jedi/intel-impi` or `jedi/gnu-impi` as before.  You should see that the GEOSpyD module has been replaced with jedi-python.

**Comment by mmiesch** [comment]
Just a quick update - the ufo-bundle tests finished with `jedi/intel-impi`.  I'm seeing a few atlas test failures but all fckit, oops, saber, ioda, and ufo tests passing.

**Comment by mmiesch** [comment]
Oh - one more thing - I confirmed with the sys admins that the default `python/GEOSpyD` module changed recently.  So, that's likely why things started failing.  For some reason the previous ones didn't cause this conflict.  So, things are starting to make sense.

**Comment by mmiesch** [comment]
One more more last thing - though it wasn't necessary to solve the problem, I did go ahead and create a new set of modules with a slightly newer version of the intel compiler.   If you want to use it, you can give this one a shot:

```
module load jedi/intel-impi/19.1.2.254
```

As for the native `comp/intel` module, version `19.1.0.166` is still the default for `jedi/intel-impi`.

**Comment by HamidehGMAO** [comment]
@mmiesch I just tried loading "jedi/intel-impi/19.1.2.254", I got this error

hebrahi1@discover35:~> module load jedi/intel-impi/19.1.2.254
Lmod has detected the following error:  Unable to load module:
     /discover/swdev/jcsda/modules/modulefiles/core/gsl_lite/0.37.0.lua: Empty or non-existant file

**Comment by mmiesch** [comment]
Ok - try now - just a permissions problem I think.

**Comment by HamidehGMAO** [comment]
Thanks @mmiesch ! It works.
