### ISSUE TITLE
GNU: Remove underflow from Fortran debug flags

### ISSUE THREAD

**Issue by ytremolet** [JCSDA/jedi-stack#17]
@jmrosinski commented on [Thu Feb 28 2019](https://github.com/JCSDA/oops/issues/165)

With build=debug under the GNU compilers, the flag -ffpe-trap=underflow is currently enabled for Fortran files. This will cause underflows (e.g. 1.e-20/1.e+20 in single precision) to abort rather than underflow to zero. Normally underflowing to zero and continuing is the preferred behavior, and is what the Intel build=debug setting provides (-fpe-all=0).

Therefore suggest removing "underflow" from the settings of CMAKE_Fortran_FLAGS_DEBUG in file cmake/compiler_flags_GNU_Fortran.cmake

**Comment by mmiesch** [comment]
Issue moved to [JCSDA/oops #457](https://github.com/JCSDA/oops/issues/457) via [**ZenHub**](https://www.zenhub.com/)
