### ISSUE TITLE
`discover` modules `gnu-impi` module `netcdf` built with wrong GFortran?

### ISSUE THREAD

**Issue by markjolah** [JCSDA/jedi-stack#178]
I'm now running into this problem when building on discover with `jedi/gnu-impi`.  This did seem to be working previously, so I'm trying to figure out what changed for me.

```
[ 57%] Building Fortran object ufo/src/ufo/CMakeFiles/ufo.dir/ufo_geovals_mod.F90.o
cd /gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ufo/src/ufo && /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpif90 -DBOOST_ALL_NO_LIB -DNDEBUG -Dufo_EXPORTS -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ufo/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ufo/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src/ufo -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/oops/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/oops/include -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/oops/GNU/9.2.0 -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/fckit/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/fckit/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/fckit/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/fckit/src/fckit -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/atlas/src/atlas_f -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/atlas/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/atlas/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/atlas/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/atlas/src/atlas_f -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ioda/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ioda/include -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/ioda/GNU/9.2.0 -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/crtm/libsrc -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/crtm/GNU/9.2.0 -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/gsw -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/gsw/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/gsw -I/usr/local/other/python/GEOSpyD/4.8.3_py3.8/2020-08-11/include -I/discover/swdev/jcsda/modules/gnu-9.2.0/impi-20.0.0.166/netcdf/4.7.4/include -I/discover/swdev/jcsda/modules/core/eigen/3.3.5/include/eigen3 -I/usr/include -I/discover/swdev/jcsda/modules/gnu-9.2.0/impi-20.0.0.166/eckit/jcsda-1.11.6.jcsda1/include -I/discover/swdev/jcsda/modules/gnu-9.2.0/impi-20.0.0.166/eckit/jcsda-1.11.6.jcsda1/include/eckit  -fno-openmp -D_REAL8_ -ffree-line-length-none -O3 -funroll-all-loops -finline-functions  -J../../module -fPIC   -fopenmp -c /gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src/ufo/ufo_geovals_mod.F90 -o CMakeFiles/ufo.dir/ufo_geovals_mod.F90.o
/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src/ufo/ufo_geovals_mod.F90:955:4:
  
  955 | use netcdf
      |    1
Fatal Error: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran
compilation terminated.

```

**Comment by mmiesch** [comment]
That is the issue we've been referring to #161 - it's because of the GEOSPyD python module

**Comment by rickgrubin** [comment]
> I'm now running into this problem when building on discover with `jedi/gnu-impi`. This did seem to be working previously, so I'm trying to figure out what changed for me.
> 
> ```
> [ 57%] Building Fortran object ufo/src/ufo/CMakeFiles/ufo.dir/ufo_geovals_mod.F90.o
> cd /gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ufo/src/ufo && /usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpif90 -DBOOST_ALL_NO_LIB -DNDEBUG -Dufo_EXPORTS -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ufo/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ufo/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src/ufo -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/oops/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/oops/include -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/oops/GNU/9.2.0 -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/fckit/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/fckit/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/fckit/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/fckit/src/fckit -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/atlas/src/atlas_f -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/atlas/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/atlas/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/atlas/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/atlas/src/atlas_f -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/ioda/src -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/ioda/include -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/ioda/GNU/9.2.0 -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/crtm/libsrc -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/module/crtm/GNU/9.2.0 -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/gsw -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/gsw/module -I/gpfsm/dnb55/molah/rapids/build/jcsda/develop/_build/gsw -I/usr/local/other/python/GEOSpyD/4.8.3_py3.8/2020-08-11/include -I/discover/swdev/jcsda/modules/gnu-9.2.0/impi-20.0.0.166/netcdf/4.7.4/include -I/discover/swdev/jcsda/modules/core/eigen/3.3.5/include/eigen3 -I/usr/include -I/discover/swdev/jcsda/modules/gnu-9.2.0/impi-20.0.0.166/eckit/jcsda-1.11.6.jcsda1/include -I/discover/swdev/jcsda/modules/gnu-9.2.0/impi-20.0.0.166/eckit/jcsda-1.11.6.jcsda1/include/eckit  -fno-openmp -D_REAL8_ -ffree-line-length-none -O3 -funroll-all-loops -finline-functions  -J../../module -fPIC   -fopenmp -c /gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src/ufo/ufo_geovals_mod.F90 -o CMakeFiles/ufo.dir/ufo_geovals_mod.F90.o
> /gpfsm/dnb55/molah/rapids/build/jcsda/develop/ufo/src/ufo/ufo_geovals_mod.F90:955:4:
>   
>   955 | use netcdf
>       |    1
> Fatal Error: Cannot read module file ‘netcdf.mod’ opened at (1), because it was created by a different version of GNU Fortran
> compilation terminated.
> ```

I've hit this before on my mac when compiling stack components against different versions of gfortran; tried to compile against a netCDF library built with GNU v9.x when using GNU v10.x to update the stack, for example.

Perhaps a conflict between whatever compiler / version this is: 

`/usr/local/intel/2020/compilers_and_libraries_2020.0.166/linux/mpi/intel64/bin/mpif90`

vs. 

`/discover/swdev/jcsda/modules/gnu-9.2.0`

**Comment by markjolah** [comment]
close as a duplicate of #178
