### ISSUE TITLE
DDT or Totalview?

### ISSUE THREAD

**Issue by ytremolet** [JCSDA/jedi-stack#22]
Please add any information or preference for a debugger.

**Comment by xinzhang8noaa** [comment]
I used Totalview a lots couple years ago, I was happy with the totalview; I also tried DDT a little bit on Cheyenne, in general, it is OK and comparable with totalview , but somehow, It crashed occasionally, and feel not that smooth as what I feel as totalview. Anyway, I don't have strong preference, either is OK.

**Comment by mmiesch** [comment]
You can download a free 1-week trial of ddt here:
https://www.arm.com/products/development-tools/server-and-hpc/forge/ddt

**Comment by srherbener** [comment]
I'm okay with either debugger.

I have some experience with DDT and I liked it, but that is from about 10 years ago.

I believe that CISL provides DDT for the debugger on Cheyenne, so there would be an advantage of consistency for people who work on Cheyenne. This might be a compelling reason for going with DDT if most of the other HPC systems also provide DDT.

**Comment by srherbener** [comment]
@mmiesch, is there a trial version of DDT for the Mac? I went to the sight above and I found downloads are for SUSE, RedHat, Ubuntu but not the Mac. Perhaps I'm looking in the wrong area.

**Comment by ytremolet** [comment]
DDT comes with MAP which is very useful for performance analysis. I don't think totalview comes with a similar tool.

**Comment by mmiesch** [comment]
No - TotalView doesn't come with a performance tool but we could always use the free tool [TAU from Oregon State](http://www.cs.uoregon.edu/research/tau/home.php).  This is a really nice parallel profiler.

**Comment by fcvdb** [comment]
TotalView was used on AWS with a license demo and the issues with running FV3 were solved.
