### ISSUE TITLE
Add TAU module to JEDI stack

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#41]
At some point we should add the TAU profiler suite to the JEDI-stack as an optional module.  It has already been used for SOCA and it can be implemented in such a way that it can be a loosely coupled additional module with no changes required to the bundle CMakeLists.txt files.

**Comment by jkbk2004** [comment]
@mmiesch I cloned jedi-stack and touched build script, config, and modulefile to see if I can build pdtoolkit (needed for tau installation) on my computer. I made feature/pdt branch and can't push it to jedi-stack repo. Permission issue. If I run /home/jkim/jedi_stack/jedi-stack/setup_environment.sh ubuntu/18.04, some complaints like --> make: /home/jkim/jedi_stack/jedi-stack/pkg/lua-5.1.4.9/build/unixType: Command not found

**Comment by mmiesch** [comment]
Thanks @jkbk2004 - I just changed it so you should be able to push to this repo now.
Regarding the ```setup_environment.sh``` script - this is mainly intended for otherwise bare systems like a new compute instance on the cloud.  For a personal computer, I would do most of this manually (and much of it, like curl, git, and wget, you likely already have).  With regard to lmod, it may be easier to install it with luarocks:
~~~~~
sudo apt-get install luarocks
sudo luarocks install luaposix
sudo luarocks install luafilesystem
~~~~~

Then you can install lmod as follows:
# this installs in $MODULESHOME, which is set to $mods_path/lmod/lmod
cd ${JEDI_STACK_ROOT}/${PKGDIR:-"pkg"}
wget https://sourceforge.net/projects/lmod/files/Lmod-$lmod_version.tar.bz2
bzip2 -d Lmod-$lmod_version.tar.bz2; tar xvf Lmod-$lmod_version.tar
cd Lmod-$lmod_version
[[ -d build ]] && rm -rf build
mkdir -p build && cd build
../configure --prefix=$mods_path
sudo make install
~~~~~
See [the lmod documentation](https://lmod.readthedocs.io/en/latest/030_installing.html) for further details

**Comment by jkbk2004** [comment]
@mmiesch mpif90 works fine to install tau. But tau doesn't support mpifort. I notice mpifort on singularity container. tau/configure says mpiifort is ok. Should I check tau mpifort issue with sameer? pdtoolkit should be installed first before tau. So, I put a line in build_tau2.sh to check pdtoolkit installed. I am not sure if I can go like this. Also, in tau configure line, I have to put pdttoolkit path. I put PDTLIB_ROOT variable in module lua file. Is there a way I can use that variable in build_tau2.sh? If I manually set some variables like MPI_FC, PDTLIB_ROOT, etc., the build_stack.sh runs ok on my note computer to install pdt and tau at /opt/modules/clang-6.0.1 I pushed feature/tau branch.

**Comment by jkbk2004** [comment]
@mmiesch it seems Lmod is not fully functional on my laptop. At least, I am not finding all available modules (thru .modulespath file). But no problem to build pdt/tau2 with scripts.

**Comment by mmiesch** [comment]
@jkbk2004 - regarding mpifort vs mpif90 - these are just wrappers defined by the MPI implementation.  The containers use openmpi.  In openmpi, mpif90 is deprecated - they used to use it but now they have moved to mpifort - [see here](https://www.open-mpi.org/faq/?category=mpi-apps#mpifort-vs-mpif77-and-mpif90).    I believe other MPI libraries are also moving from mpif90 to the more general mpifort (though HPE MPT is an exception - they still use mpif90).

However, both mpifort and mpif90 are defined in the container and they are identical - both are just links to the same thing:  
~~~~~
Singularity singularity_latest.sif:/usr/local/bin> ls -l mpi*
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpiCC -> opal_wrapper
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpic++ -> opal_wrapper
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpicc -> opal_wrapper
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpicxx -> opal_wrapper
lrwxrwxrwx 1 root root  7 Aug  2 04:07 mpiexec -> orterun
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpif77 -> opal_wrapper
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpif90 -> opal_wrapper
lrwxrwxrwx 1 root root 12 Aug  2 04:08 mpifort -> opal_wrapper
lrwxrwxrwx 1 root root  7 Aug  2 04:07 mpirun -> orterun
~~~~~

**Comment by mmiesch** [comment]
@jkbk2004 - I'm not sure what you mean by lmod not being fully functional.  In order to see the modules of the jedi-stack you have to build them and install them.  lmod is used to manage the module files but it does not build them.  In any case, I can test this on my Mac and on AWS (ubuntu) when you think it is ready.  In both environments I can try building it as an extension to the pre-existing jedi stack.

**Comment by jkbk2004** [comment]
@mmiesch that's good idea if you try to build on top of existing jedi-stack. But let's do that after I talk to Sameer about tau/mpifort issue. I am waiting for his email about this. I installed Lmod on my laptop and set up jed/pdtoolkit/tau2 modules. module avail doesn't recognize whatever extra modules I put. Maybe I will figure out later. One question is about how to bring in tau2 installation/modules (locally installed on my laptop) inside singularity.

**Comment by mmiesch** [comment]
Thanks @jkbk2004 - you may just have to add the path with a ```module use``` command.  jedi-stack is set up to install modules in the ```$OPT``` directory, where the ```$OPT``` environment variable is set to ```/opt/modules``` by default.  To be able to access the modulefiles with lmod, you need to add this to your MODULEPATH with:
~~~~~
module use $OPT/modulefiles/core
~~~~~
Then other modules such as TAU should become accessible as you load a particular compiler/mpi combination.  But, note that this works a little differently in the containers because the containers do not currently use modules.

**Comment by mmiesch** [comment]
Regarding how to use tau in singularity - after we confirm that everything works outside the container then we can consider building new containers with tau pre-installed.  If you want to use it before then, you can try [mounting the Tau directories with the -B option](https://sylabs.io/guides/3.3/user-guide/bind_paths_and_mounts.html) and then adding them to your ```PATH``` and ```LD_LIBRARY_PATH``` environment variables (along with setting any other environment variables that may be needed).

**Comment by jkbk2004** [comment]
@mmiesch great! Let's move after getting some idea tau/mpifort issue.

**Comment by jkbk2004** [comment]
@mmiesch in tau2.lua, can I specify a makefile name inside pathJoin? like
setenv("TAU_MAKEFILE", pathJoin(base,"x86_64/lib/Makefile.tau-ompt-tr4-mpi-pdt-openmp"))

**Comment by mmiesch** [comment]
Yes, that should work.  Although, technically speaking one should be consistent with either using pathJoin to concatenate strings or not.  So, better style might me either this:
~~~~~
setenv("TAU_MAKEFILE", pathJoin(base,"x86_64","lib","Makefile.tau-ompt-tr4-mpi-pdt-openmp"))
~~~~~
or this
~~~~~
setenv("TAU_MAKEFILE",base..""x86_64/lib/Makefile.tau-ompt-tr4-mpi-pdt-openmp")
~~~~~
The first is probably preferable
