### ISSUE TITLE
Build jedi-stack on discover

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#52]
As a supplement to existing baslibs stack.

**Comment by mmiesch** [comment]
So, I started to do this this week and realized that Discover uses tcl modules rather than lua.  This means that installing jedi-stack there would be a bit inconvenient, unless someone knows of a tool to automatically convert lua modulefiles to tcl (I know lmod has a tool for the other way around).  It would be straightforward to create a tcl version of the jedi-stack modulefiles but it would be a bit tedious to maintain unless we really need it.  Since we have the baselibs version of the libs working on Discover, this doesn't seem to be that high of a priority.  What do you think?

**Comment by danholdaway** [comment]
I agree that it shouldn’t be a priority. We have what we need for now and there are likely changes coming to Discover, e.g. move to lua modules so might not be worth going through the process of creating tcl modulefiles unless it’s useful elsewhere. Thanks for looking into this.
