### ISSUE TITLE
discover FindLAPACK (MKL) failure

### ISSUE THREAD

**Issue by markjolah** [JCSDA/jedi-stack#59]
The jedi-stack module `jedi/intel17-impi` on discover uses the system MKL libraries to provide LAPACK support.  CMake requires some additional environment variables for MKL to be correctly discovered as the LAPACK provider.  

Symptom of failing build:
```
CRITICAL - oops FAILED to find package LAPACK

      Provide location by defining "-DCMAKE_PREFIX_PATH= /..." or with "-DLAPACK_PATH=/..." or "-DLAPACK_DIR=/..." 
      You may also export environment variables LAPACK_PATH or LAPACK_DIR
    Values (note CAPITALISATION):
      LAPACK_PATH should contain the path to the install prefix (as in <install>/bin <install>/lib <install>/include)
      LAPACK_DIR should be a directory containing a <package>-config.cmake file (usually <install>/lib/cmake/<package>)

  !! oops requires package LAPACK !!
```

Provided MKL module info:
```
/usr/local/share/modules/modulefiles.slurm/lib/mkl-17.0.7.259:

module-whatis	 loads the lib/mkl-17.0.7.259 environment 
system		 /bin/logger -p local2.info envmodule display lib/mkl-17.0.7.259 
setenv		 INTEL_LICENSE_FILE /usr/local/intel/license 
setenv		 MKLROOT /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl 
setenv		 MKLPATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/lib/intel64 
prepend-path	 INCLUDE /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/include 
prepend-path	 LD_LIBRARY_PATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/lib/intel64 
prepend-path	 LD_LIBRARY_PATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/compiler/lib/intel64_lin 
prepend-path	 MIC_LD_LIBRARY_PATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/lib/mic 
prepend-path	 LIBRARY_PATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/lib/intel64 
prepend-path	 LIBRARY_PATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/compiler/lib/intel64_lin 
prepend-path	 CPATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/include 
prepend-path	 FPATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/include 
prepend-path	 NLSPATH /usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/lib/intel64/locale/%l_%t/%N 
```
To this we need to add the following environment variables:
```
LAPACK_PATH=/usr/local/intel/2017/compilers_and_libraries_2017.7.259/linux/mkl/
BLA_VENDOR=Intel10_64lp_seq
```

Note that the second variable chooses the version of MKL to use.  This is the 64-bit API, without threads, and using 32-bit integer indexing.  I believe this is the right version to use for all JEDI applications, if those options are not correct the other options can be found in the [CMake FindLAPACK Documentation](https://cmake.org/cmake/help/latest/module/FindLAPACK.html).

Suggest we provide our own version of the above module with the additional environment variables.

**Comment by mmiesch** [comment]
I just tried setting all of these variables on Cheyenne, along with ```BLA_STATIC=ON``` and ```LAPACK_LIBRARIES="libmkl_lapack95_lp64.a;libmkl_blas95_lp64.a"``` for good measure, but it still did not work.  When I build eckit, it finds mkl just fine, enables mkl, and does not complain about LAPACK.  But, when I try to build ufo-bundle, it still complains.

**Comment by mmiesch** [comment]
@markjolah - did you try setting those environment variables manually on Discover and compile?  Did it work?

**Comment by mmiesch** [comment]
Maybe the problem is not with cmake or ecbuild, but with JEDI.  
The top-level CMakeLists.txt file in eckit handles MKL and lapack like this:
~~~~~
### LAPACK

if( ECKIT_HAVE_MKL )
    set( ECKIT_HAVE_LAPACK 1 )
    set( LAPACK_LIBRARIES ${MKL_LIBRARIES} )
else()
    ecbuild_add_option( FEATURE LAPACK
                        DESCRIPTION "Linear Algebra PACKage"
                        REQUIRED_PACKAGES "LAPACK QUIET" )
endif()
~~~~~

And, eckit has no problem building with mkl in place of lapack.  But, in oops and other jedi repos, we just have this:
~~~~~
# LAPACK
ecbuild_add_option( FEATURE LAPACK
                    DESCRIPTION "Linear Algebra PACKage"
                    REQUIRED_PACKAGES "LAPACK REQUIRED" )
if (NOT HAVE_LAPACK)
  ecbuild_error("LAPACK_LIBRARIES not defined")
endif()
~~~~~
