### ISSUE TITLE
Which ecbuild version is being used in the containers?

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/jedi-stack#64]
https://github.com/JCSDA/jedi-stack/blob/develop/buildscripts/build_stack.sh#L101 indicates that JCSDA/ecbuild is being used with the feature/test_lists branch, but this branch no longer exists.

This matters for the jedi-build app, because different versions of ecbuild install cmake package files in different locations.

**Comment by mmiesch** [comment]
HI @rhoneyager - Yes, the current containers contain the ```feature/test_lists``` branch, which no longer exists - it has been merged into develop.  As mentioned in our meeting yesterday, I plan to define a tagged version of our fork as ```3.1.0.jcsda1```.  However, before doing that I want to merge [this PR](https://github.com/JCSDA/ecbuild/pull/19) to get our fork up to date with ecmwf develop.  I need at least one approval before I can merge.  As soon as I get an approval, I will merge, create the tag, and generate the new containers.
Note - new builds should also use the 1.4.0.jcsda2 tag of eckit.  I'll modify jedi-stack accordingly after I merge ecbuild.  And I'll add you to the ecbuild review.

**Comment by rhoneyager** [comment]
Thanks for working on this.
