### ISSUE TITLE
BLAS?

### ISSUE THREAD

**Issue by rhoneyager** [JCSDA/jedi-stack#76]
Is BLAS a requirement? I'm building the gcc 9.2.0 stack on hera, and this is the first system I've seen where oops fails to configure because of a missing blas dependency.

I guess normally it is provided by mkl which masks the dependency, but there is no gfortran build of this on hera.

**Comment by mmiesch** [comment]
Hmm.. I haven't seen that before.  What compilers are you using?  Normally, if I'm using intel, I'll use mkl to provide the BLAS functionality.  For gnu or clang compilers, I would build LAPACK - there is a build script and modulefile setup for this in jedi-stack.

**Comment by rhoneyager** [comment]
See above. It's a bare install on gcc+gfortran 9.2.0, with openmpi 3.1.4. Adding in LAPACK fixes it, of course, though it was unexpected.

**Comment by aerorahul** [comment]
That is interesting because, on my Linux workstation, I use MKL with GCC 9.2.0 and have no issues finding BLAS.

**Comment by mmiesch** [comment]
Yes - mkl is another option - I haven't used it with gnu but I know it can be done.  I don't know which is more efficient.  But, when we're worried about efficiency we'll probably use intel anyway.

**Comment by aerorahul** [comment]
@mmiesch I agree.  I am not suggesting we use MKL with GNU at the moment.  I am simply stating that MKL with GNU can be used and the issue then must be on Hera.  Hera must not have a complete/correct installation of MKL.

**Comment by rhoneyager** [comment]
They do have an installation of MKL. It's just bundled up with their Intel compiler installations. This particular stack build, though, is intended to be independent of any of the Intel components.

**Comment by markjolah** [comment]
MKL with gnu works fine, and we have recently modified OOPS so it will prefer to link against MKL if it is found, no matter the compiler.   The easiest solution if you don't want/have MKL is to use LAPACK.  I suspect we're not very BLAS operation heavy, so I doubt there is much performance drop-off.  If you want opensource and more performance, I normally link against openblas on my gentoo systems, and that also works, but you'd have to add a jedi-stack build script and module.
