### ISSUE TITLE
During ufo-bundle build Atlas is unable to find LateX

### ISSUE THREAD

**Issue by jintaglee** [JCSDA/jedi-stack#86]
I am trying to build ufo-bundle (`develop` branch at 25d25ff) with documentation-generation switched on (in the top-level CMakeLists.txt),
```
option(BUILD_UFO_BUNDLE_DOC "Build documentation" ON)
```
It appears during the build of Atlas ecbuild/cmake is not able to find Latex (among other packages).

To increase the verbosity level when ecbuild runs I ran ecbuild with the following commandline options,
```
ecbuild -- --trace --trace-expand --trace-redirect=out.trace.txt ../../ufo-bundle
```
In `out.trace.txt` trace log there are following lines,
```
/g/data/dp9/jtl548/opt/modules/core/ecbuild/jcsda-3.1.0.jcsda2/share/ecbuild/cmake/compat/ecbuild_compat_require.cmake(149):  find_package(Latex )
/g/data/dp9/jtl548/source/jedi/ufo-bundle/atlas/cmake/FindLatex.cmake(12):  FIND_PROGRAM(PDFLATEX NAMES pdflatex PATHS /usr/local/share/apps/TeXLive/2014/bin/x86_64-linux/ )
...
/g/data/dp9/jtl548/opt/modules/core/ecbuild/jcsda-3.1.0.jcsda2/share/ecbuild/cmake/ecbuild_add_option.cmake(211):  ecbuild_info(Could NOT find package Latex required for feature DOCS -- Provide Latex location with -DLATEX_PATH=/... )
```
When I look at `FindLatex.cmake` the relevant lines for finding LateX tools are,
```
# find latex libraries
FIND_PROGRAM (PDFLATEX
              NAMES pdflatex
              PATHS /usr/local/share/apps/TeXLive/2014/bin/x86_64-linux/)
FIND_PROGRAM (BIBTEX
              NAMES bibtex
              PATHS /usr/local/share/apps/TeXLive/2014/bin/x86_64-linux/)
...
```
On our HPC LaTeX tools are installed under /usr/bin (and /bin) so this explains why Atlas' `FindLatex.cmake` cannot find LaTeX.

Steve Herbener suggested using `-DLATEX_PATH=/usr/bin` to force cmake to use our installation location but this did not work.

One thing that puzzles me is: why does Atlas have its own `FindLatex` macro. cmake's own macro, `FindLATEX.cmake` has correct search paths,
```
find_program(LATEX_COMPILER
  NAMES latex
  PATHS ${MIKTEX_BINARY_PATH}
        /usr/bin
)

# find pdflatex
find_program(PDFLATEX_COMPILER
  NAMES pdflatex
  PATHS ${MIKTEX_BINARY_PATH}
        /usr/bin
)
...
```

**Comment by jintaglee** [comment]
Similar problem occurs with other packages as well. For example, Steve spotted in the log output that during the fckit build it was not able to find FORD. 

Steve also mentioned that he tried to build ufo-bundle with the documentation-generation turned on on an iMac inside the CharlieCloud container (Ubuntu). He saw the same error.

**Comment by jintaglee** [comment]
Hi @mmiesch and @srherbener, I submitted an issue following Steve's advice. I'm not sure how to proceed from here. Would you be able to help me?

**Comment by ytremolet** [comment]
I've had issues in the past with another package (I forgot which one now) that was in /usr/lib instead of /usr/local/lib and that ecbuild/cmake could not find. Is that a general issue?
Also tagging @markjolah who might have some input.

**Comment by aerorahul** [comment]
@jintaglee 
The `atlas::cmake/FindLatex.cmake` is faulty.  It is hard-wired for an 2014 installation of Latex on a macOS.  It should be removed. 
The correct one to use is `FindLATEX.cmake` that cmake provides as part of its build.
The edit should be made in `cmake/features/DOCS.cmake`
The line `find_package(Latex)` should be replaced with `find_package(LATEX)`. The `CONDITION` should be updated to `LATEX_FOUND`.

On Unix, you may encounter more issues, but you should atleast be able to create a pdf documentation.

**Comment by aerorahul** [comment]
See [jcsda::atlas PR 10](https://github.com/JCSDA/atlas/pull/10)

**Comment by jintaglee** [comment]
@aerorahul, as you suggested I made the following change in `atlas::CMakeLists.txt`,
```
 ecbuild_add_option( FEATURE DOCS
                     DESCRIPTION "Atlas documentation"
                     DEFAULT OFF
-                    REQUIRED_PACKAGES "Latex" )
+                    REQUIRED_PACKAGES "LATEX" )
```
This time it looks like ecbuild/cmake found some LaTeX tools but not all: xelatex, biber, xindy, dvipdf, pdftops, latex2html and htlatex were not found because on our HPC they are not installed at the location that cmake expects (/usr/bin).

I then ran `make` which succeeded but I don't see any pdf files: for example, under \<build- directory\>/Documentation/html there is an HTML file, "_overview.html" which has following links,

* "A short description of the two-level quasi-geostrophic model." -> two_level_qg.pdf
* "Formulation of Weak Constraint 4D-Var." -> weak_4dvar.pdf
* "Documentation of the OOPS Linear Equation Solvers." -> solvers.pdf

These pdf files don't seem to exist. Could this be because some of the LaTeX tools were not found?

**Comment by aerorahul** [comment]
@jintaglee 
There are 2 separate issues here.
To make atlas documentation, you have to execute `make atlas_doc`.
To enable UFO/OOPS/IODA documentation, there are other flags. 
The ufo-bundle has an optional argument during ecbuild `-DBUILD_UFO_BUNDLE_DOC=ON|OFF`
To build OOPS docs, the argument with ecbuild is `-DBUILD_OOPS_DOC=ON|OFF`

If your latex installation does not have all the components, you may not be able to build all types of documentations; e.g. pdf, html.

You can test if check what your latex installation is by doing:
`find_package(LATEX REQUIRED COMPONENTS PDFLATEX BIBTEX MAKEINDDEX HTLATEX)`
You must have the first 2 for pdf documentation of atlas, the other 2 are for HTML.

**Comment by jintaglee** [comment]
Hi @aerorahul, when I check our latex installation I get the following,
```
gadi-login-02:/home/548/jtl548/doc/cmake/examples/check_latex_installation/build> cmake ..
CMake Error at /apps/cmake/3.16.2/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find LATEX (missing: MAKEINDDEX HTLATEX)
```
So our installation does not have all the tools needed, which confirms what I'm seeing.

I contacted the sysadmin for our HPC and they are reluctant to install all the tools needed for JEDI document generation under /usr/bin. I would've thought this is not just a problem at our site alone and other HPC centers must have similar issues: software packages not installed on a specific location. Is there a general solution which will allow JEDI documentation builds to be more portable with regard to the LaTeX-related tools?

**Comment by ytremolet** [comment]
Maybe HPC systems are not the place to generate the documentation. It could be done on workstations. What do you think?

**Comment by aerorahul** [comment]
> Maybe HPC systems are not the place to generate the documentation. It could be done on workstations. What do you think?

Normally I would agree, but some documentation (e.g. Atlas) has in-line code that needs to be compiled during the documentation building.

**Comment by aerorahul** [comment]
> Hi @aerorahul, when I check our latex installation I get the following,
> 
> ```
> gadi-login-02:/home/548/jtl548/doc/cmake/examples/check_latex_installation/build> cmake ..
> CMake Error at /apps/cmake/3.16.2/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
>   Could NOT find LATEX (missing: MAKEINDDEX HTLATEX)
> ```
> 
> So our installation does not have all the tools needed, which confirms what I'm seeing.
> 
> I contacted the sysadmin for our HPC and they are reluctant to install all the tools needed for JEDI document generation under /usr/bin. I would've thought this is not just a problem at our site alone and other HPC centers must have similar issues: software packages not installed on a specific location. Is there a general solution which will allow JEDI documentation builds to be more portable with regard to the LaTeX-related tools?

To be clear, the PDF Atlas documentation only requires PDFLATEX_COMPILER and BIBTEX_COMPILER . You need the other MAKEINDEX_COMPILER and HTLATEX_COMPILER if you wish to create html documentation from the pdf documentation.  So, you can simply do `make atlas_doc_pdf` and still get a pdf of the users-guide.

**Comment by mmiesch** [comment]
@aerorahul - is that true or do we need to declare HTLATEX and MAKEINDEX optional components in the find_package(LATEX) call?

**Comment by aerorahul** [comment]
> 
> 
> @aerorahul - is that true or do we need to declare HTLATEX and MAKEINDEX optional components in the find_package(LATEX) call? 

I’ll amend my PR on the ecmwf repo to make them OPTIONAL_COMPONENTS for documentation creation.

**Comment by aerorahul** [comment]
> 
> 
> @aerorahul - is that true or do we need to declare HTLATEX and MAKEINDEX optional components in the find_package(LATEX) call? 

Yes. It is true. You only need pdflatex to create pdf documentation. I do that on my Linux workstation.

**Comment by mmiesch** [comment]
I was just suggesting that the find_package() needs to be modified so it doesn't return false if HTLATEX and MAKEINDEX aren't there.

In any case, I think this is a reasonable compromise.  I think it can be useful to generate different bits of the documentation depending on what you have installed on your system - we shouldn't omit things for portability reasons in this case.  For more, one can move to a laptop - or, eventually, consult the web.  For releases we plan to publish documentation on the web (and in the containers), including doxygen.    Hopefully ECMWF will do the same so we can link to their atlas documentation.  If not we'll coordinate a way to make it available for those who cannot generate it themselves.

**Comment by jintaglee** [comment]
I will try using a container as suggested by @ytremolet. Hopefully this will get around any issues related to software stack.

**Comment by mmiesch** [comment]
I don't think ford and htlatex are available in the current containers but we can add them in the next round.  pdflatex and doxygen are there.

**Comment by jintaglee** [comment]
No worries. I can wait until ford and htlatex are available. How do I get informed of a new release? Should I put my name under the "Watch" in this github board?

**Comment by mmiesch** [comment]
There's another zenhub issue - I'll add you to that so you'll get emails when anything changes.  Also, when new containers are available I'll announce it on the [JEDI Team page](https://github.com/orgs/JCSDA/teams/jedi). Currently I'm waiting for reviews on [this PR](https://github.com/JCSDA/ecbuild/pull/28)

**Comment by mmiesch** [comment]
@jintaglee - I meant to also recommend that you "Watch" the JEDI team page by selecting the drop-down menu on the left.  This is where we post many important announcements - if you watch it you'll be notified by email when there is a new post

**Comment by jintaglee** [comment]
Hi @mmiesch. thanks for pointing out the JEDI Team page. Much appreciated.
