### ISSUE TITLE
generate new development containers (gnu, clang, intel17, intel19)

### ISSUE THREAD

**Issue by mmiesch** [JCSDA/jedi-stack#87]
New features

- [x] odc public release (jcsda fork)
- [x] pyodc public release (jcsda fork?)
- [x] ecbuild: define a new tag for jcsda fork
- [x] gnu time
- [x] htlatex
- [x] ford
- [x] imagemagick

Is there anything else you'd like to see included?

**Comment by srherbener** [comment]
I think the list looks good. The pyodc is definitely coming from the JCSDA fork.

**Comment by rhoneyager** [comment]
For Intel19, are we sticking with 19.0 or moving to 19.1, which is now marketed as Intel 2020?

**Comment by rhoneyager** [comment]
Also, could we do a census to see who still needs Intel 17? Intel 18 and later have much better C++17 support.

**Comment by srherbener** [comment]
Good point @rhoneyager, I think the sooner we can move off of Intel17 the better. Another motivation is the performance issue with Intel17 that @mmiesch, @danholdaway and I have been experiencing on S4.

**Comment by mmiesch** [comment]
@srherbener - I suspect that performance issue is specific to S4 - Jesse confirms that the infiniband drivers may not be configured correctly.  I do not think this is an issue in the containers or on any other systems where I haven't noticed much of a difference in performance with intel 17 vs 19.

The problem with intel 19 is with the size of the containers, since the silent component install does not work so everything is installed.  That bug has not been fixed in intel 19.1 / Parallel Studio 2020.  I may be able to get around that another way but I haven't had the chance to play with it yet.

Regarding intel 19.0.5 vs 19.1 - I would prefer to stick with what we have (19.0.5) unless there is a good reason not to.  Particularly for the HPC containers, many paths and components have to be specified manually so doing an upgrade can be time-consuming.

**Comment by mmiesch** [comment]
Adding to the estimate here because it involved upgrading to gnu 9.3 and intel 19
