### ISSUE TITLE
Install jedi-stack on Gadi for a general use

### ISSUE THREAD

**Issue by jintaglee** [JCSDA/jedi-stack#93]
The branch used is feature/gadi.

**Comment by jintaglee** [comment]
Hi @wenming.lu@bom.gov.au, I've consolidated the build instruction and now you can find it in the following link,

https://github.com/JCSDA/jedi-stack/blob/feature/gadi/doc/platforms/gadi.md

**Comment by wenminglu-bom** [comment]
@jintaglee 

Summary of Building

1. /projects/access/apps/jedi/jedi-stack_1.0 is the codes checked out as feature/gadi.

2. Changes made in 
/projects/access/apps/jedi/jedi-stack_1.0/buildscripts/config/config_nci_gnu8.2.1-openmpi3.1.4.sh
export PREFIX=/g/data/dp9/jtl548/opt/modules
to
export PREFIX=/projects/access/apps/jedi/1.0

Ditto for config_nci_gnu8.2.1-openmpi4.0.2.sh

3.  In modulefiles_tcl
Replace all 
/g/data/dp9/jtl548/opt/modules
with 
/projects/access/apps/jedi/1.0/

4. export OPT=/projects/access/apps/jedi/1.0

5. Installation dir is
/projects/access/apps/jedi/1.0

6. Building log files at
/projects/access/apps/jedi/jedi-stack_1.0/buildscripts
bld_err.txt  
bld_out.txt

7. Module file at
/projects/access/modules/jedi/1.0

Test to be done

**Comment by jintaglee** [comment]
Hi @wenminglu-bom, I updated the scripts and modulefiles to replace all instances of my personal directory name with $OPT. I pushed the changed to the feature/gadi branch.

So at the start of your build do,

```
 export OPT=/projects/access/apps/jedi/v0.0
```

Please note that my branch (feature/gadi) pre-dates jedi-stack release v0.1 so I think our installation should have a version, "v0.0" to be consistent with JCSDA version naming.

Can you try again?

**Comment by wenminglu-bom** [comment]
Hi @jintaglee 
Done for the latest one. You may test this way,

export OPT=/projects/access/apps/jedi/v0.0
module load jedi_wrapper/0.0
module load jedi/gcc-system_openmpi-3.1.4

Of course, you need to run the last one twice to load tons of modules by system and then load jedi/gcc-system_openmpi-3.1.4. I do not know how to do the test on ufo and fv3. If you could elaborate a bit more, I am happy to do it.

**Comment by wenminglu-bom** [comment]
@jintaglee 

The only problem I have now is that we must 

export OPT=/projects/access/apps/jedi/v0.0

I hope it is better to get this one done in the module file but so far I have not succeeded.

**Comment by wenminglu-bom** [comment]
@jintaglee 
Sorry just got an idea to setenv in the module file as
setenv OPT /projects/access/apps/jedi/v0.0

So now, it is two step
module load jedi_wrapper/0.0
module load jedi/gcc-system_openmpi-3.1.4

I deliberately use jedi_wrapper to avoid conficts with  jedi/gcc-system_openmpi-3.1.4.

**Comment by jintaglee** [comment]
Versions of jedi-stack seem to be managed by attaching different versions of components to jedi-stack. For example, for the `ecbuild` tool in jedi-stack the installation directory is,
```
$OPT/core/ecbuild/jcsda-3.1.0.jcsda2
```
The version of the tool, "ecbuild" is `jcsda-3.1.0.jcsda2`.

For a modulefile,
```
$OPT/modulefiles/mpi/gcc/system/openmpi/3.1.4/eckit/jcsda-1.4.0.jcsda3
```
The directory structure says that this modulefile is for the eckit tool version, `jcsda-1.4.0.jcsda3` which was built using OpenMPI 3.1.4 using the system version of GCC.

So the upshot is that the version you gave - `v0.0` - is not really necessary. All the tools, modulefiles, etc. can go straight under `/projects/access/apps/jedi` without the need for a jedi-stack version label.

I note though that this way of labeling versions is not strictly followed and there are a few exceptions.

So I think it's safe to set OPT to,
```
/projects/access/apps/jedi
```

I can see why you had to use the modulefile, ` jedi_wrapper`. I think a way to avoid creating another modulefile is to put `module use` in the main modulefile, `jedi/gcc-system_openmpi-3.1.4`. If you don't have any objection I will try and see if I can modify `jedi/gcc-system_openmpi-3.1.4`.

**Comment by mmiesch** [comment]
Actually, we just started implementing tags for jedi-stack: [see here](https://github.com/JCSDA/jedi-stack/releases).  This was mainly done because updates to ecbuild, eckit, and odc were breaking the jedi-rapids near-real-time workflow.  So, we wanted to define stable versions.

The `.jcsda*` labels on our ecmwf forks (ecbuild, eckit, fckit, atlas, odc, pyodc) have in the past usually referred to changes we have made relative to upstream versions.  However, in the last month we have made a new effort to start synchronizing the develop and master branches of our forks more closely with upstream (ecmwf).  So, we should soon be able to use tagged versions of the ecmwf repos in place of our jcsda forks.  But, we're not there quite yet.  And, to avoid potential delays while they review our upstream pull requests, we may still tag some of our forks with `.jcsda*` when they have changes we need right away.  So, the bottom line is that it's still advisable to use the jcsda forks for those repos but these should soon be interchangeable with the upstream versions.

**Comment by mmiesch** [comment]
I should also add that the jedi stack tags only really refer to the apps modules that load all the others - the tags define a combination of different versions of things that work well together.  So, as @jintaglee says, there is no need to tag the individual modules with version numbers.  All the version and build information is already there in the structure of the modulefiles directory.  And, jedi-stack is set up so that  you can always add components as you wish.  For example, if you want to update to a new eckit you can just install the new one and keep the old one around.  Or, if you decide you need an optional package like PIO you can always add it.   It is very flexible and customizable - designed for developers as well as users.

**Comment by jintaglee** [comment]
Hi @mmiesch, should we then include the tag name as a part of the directory structure of our jedi-stack installation? This means we can have multiple tagged jedi-stack installations available on disk.

**Comment by wenminglu-bom** [comment]
@jintaglee @mmiesch 
I think I have pretty much got the idea what Jin wants to do. I do not think I have fully understood Mark's comment but I guess I do not need to put JEDI in apps. Actually, JEDI itself has a structure of maintaining various of packages with variant version. Am I right?
Id that is the case, I do not need to create a module file for JEDI, rather, JEDI itself is an environment similar to apps.

**Comment by mmiesch** [comment]
Maybe an illustration will help explain my comment a bit more.  This is how things are set up now on S4.   

```
[mmiesch@s4-submit jedi]$ module avail jedi

------------------------------------------------------ /data/users/mmiesch/modules/modulefiles/core -------------------------------------------------------
   jedi-intel/17.0.6 (D)    jedi-intel/19.0.5    jedi/intel17-native-netcdf    jedi/intel19-impi-v0.1    jedi/intel19-impi
   jedi-intel/18.0.3        jedi/intel17-impi    jedi/intel18-impi             jedi/intel19-impi-v0.2    jedi/singularityvars (D)

```

The function of each of these top-level modules is just to load other modules.  For example, if you actually look at one of the modulefiles, it is just a list of other modules to load, some native, some built by jedi-stack:

```
[mmiesch@s4-submit jedi]$ cat $OPT/modulefiles/core/jedi/intel19-impi-v0.1.lua
help([[
Load environment for running JEDI applications with GNU compilers and OpenMPI.
]])

local pkgName    = "intel-impi"

conflict(pkgName)

load("miniconda")
load("license_intel")
load("jedi-intel/19.0.5")
load("szip/2.1.1")
load("zlib/1.2.11")
load("jedi-impi/19.0.5")
load("udunits/2.2.26")

load("hdf5/1.10.5")
load("pnetcdf")
load("netcdf/4.7.0")

load("boost-headers/1.68.0")
load("eigen/3.3.5")
load("bufrlib/master")

load("nccmp/1.8.6.5")

load("ecbuild/jcsda-feature-ecmwf-synch")
load("eckit/jcsda-1.4.0.jcsda3")
load("odc/jcsda-1.0.2.jcsda1")

setenv("CC","mpiicc")
setenv("FC","mpiifort")
setenv("CXX","mpiicpc")

whatis("Name: ".. pkgName)
whatis("Category: Application")
whatis("Description: JEDI Environment with Intel19")
```

So, the user can just load one module and have everything they need:

```
[mmiesch@s4-submit jedi]$ module load jedi/intel19-impi-v0.1.lua
[mmiesch@s4-submit jedi]$ module list

Currently Loaded Modules:
  1) miniconda/3.7-base   6) szip/2.1.1        11) pnetcdf/1.11.2        16) nccmp/1.8.6.5
  2) license_intel/S4     7) zlib/1.2.11       12) netcdf/4.7.0          17) ecbuild/jcsda-feature-ecmwf-synch
  3) impi/19.0.5          8) jedi-impi/19.0.5  13) boost-headers/1.68.0  18) eckit/jcsda-1.4.0.jcsda3
  4) intel/19.0.5         9) udunits/2.2.26    14) eigen/3.3.5           19) odc/jcsda-1.0.2.jcsda1
  5) jedi-intel/19.0.5   10) hdf5/1.10.5       15) bufrlib/master        20) jedi/intel19-impi-v0.1
```
 
This is what I mean by "apps" or "meta-modules" - all they do is load other modules.  And, you see here that these have the v0.1 and v0.2 labels for jedi stack.  The only difference is that they load different versions of ecbuild, eckit, and odc:

```
[mmiesch@s4-submit jedi]$ diff intel19-impi-v0.1.lua intel19-impi-v0.2.lua 
27,29c27,29
< load("ecbuild/jcsda-feature-ecmwf-synch")
< load("eckit/jcsda-1.4.0.jcsda3")
< load("odc/jcsda-1.0.2.jcsda1")
---
> load("ecbuild/jcsda-3.3.0.jcsda3")
> load("eckit/jcsda-1.10.1.jcsda1")
> load("odc")
```

So, there is no need to label directories with v0.1 or v0.2 - just the meta-modules that load the combination.  Now let's say we come out with a new tag on eckit.  Just install this with jedi-stack and then define a new meta-module file that loads it.  You can call this v0.3 if you wish, but it's a good idea to choose tags that are consistent with the jedi-stack releases.  Does this make sense?

**Comment by wenminglu-bom** [comment]
@mmiesch @jintaglee 
It makes sense to me or at least I think I get the idea. I will talk to Jin on what we should go ahead.

**Comment by jintaglee** [comment]
@mmiesch, you say "Now let's say we come out with a new tag on eckit", do you mean a tag of a particular commit of eckit or a tag of a particular commit of jedi-stack? If a new version of eckit is released and jedi-stack needs to use it then because of dependency other packages will need to be changed as well. This means then jedi-stack will need to be rebuilt (?) I know the build scripts of jedi-stack are flexible and allows installation of individual packages but I thought the whole idea of tags as used in jedi-stack is so that all the packages under a given tag are consistent and so dependencies are taken care of.

So in your example of a new eckit release shouldn't you build the entire jedi-stack and give it a new tag name rather than building eckit only and then creating a new meta-module and a new module for eckit?

**Comment by mmiesch** [comment]
@jintaglee - yes, you're right.  When I say a new version of eckit, I mean, for example `eckit/jcsda-1.10.1.jcsda2`.   This will probably be associated with a new jedi-stack tag of, e.g. v0.3.  However, if this is the only change, if this change is not essential, and if the code is backward compatible, we may not decide to immediately define a new jedi-stack release.   But, you could still install and use `eckit/jcsda-1.10.1.jcsda2` in your meta-module if you wish, anticipating the next jedi-stack release.  Or, you could just wait until the next jedi-stack release.  But, you would not have to re-install netcdf, eigen, lapack, etc...  You could just use what is already there, as demonstrated by the v0.1 and v0.2 example above.

**Comment by jintaglee** [comment]
@mmiesch, that's now very clear. Thank you very much for helping us! Much appreciated.

**Comment by jintaglee** [comment]
@wenminglu-bom, I notice that ~access has a subdirectory, `da` which would be a better place to put jedi-stack since JEDI is a DA infrastructure. So I suggest,
```
export OPT=/projects/access/da/jedi/jedi-stack
```

**Comment by jintaglee** [comment]
@wenminglu-bom, as agreed I have started a wiki describing the build/install of jedi-stack as well as testing. Go to https://accessdev.nci.org.au/trac/wiki/access and then find the heading, `Joint Effort for Data Assimilation Integration (JEDI)`. You will see some links from there. The link that documents installation and testing at NCI is [JEDI at NCI](https://accessdev.nci.org.au/trac/wiki/access/JEDIAtNCI).

**Comment by wenminglu-bom** [comment]
@jintaglee 
Does this look alright to you?

I checked out the source to
/projects/access/da/jedi/jedi/jedi_gadi
which is the branch of feature/gadi.

After 
export OPT=/projects/access/da/jedi/jedi-stack

There are in /projects/access/da/jedi/jedi-stack after building
core  gcc-system  modulefiles  pyjedi

When loading the module,
unset PYTHONPATH 
export OPT=/projects/access/da/jedi/jedi-stack                                        
module purge
module use /projects/access/da/jedi/jedi-stack/modulefiles/core
module use /projects/access/da/jedi/jedi-stack/modulefiles/apps
module load jedi/gcc-system_openmpi-3.1.4

**Comment by jintaglee** [comment]
Yes, it looks good.

One minor point: `module use /projects/access/da/jedi/jedi-stack/modulefiles/core` is not needed now as this is done in the modulefile, `jedi/gcc-system_openmpi-3.1.4`.

**Comment by jintaglee** [comment]
@wenminglu-bom, it looks like there are some files which do not have group/world read/execute permission: e.g.
```
$OPT/gcc-system/openmpi-3.1.4/tau2/2.28.1/x86_64/binutils-2.23.2/include/gdb
$OPT/gcc-system/openmpi-3.1.4/tau2/2.28.1/x86_64/binutils-2.23.2/include/elf
...
```
Would you be able to change the permission levels?

**Comment by wenminglu-bom** [comment]
@jintaglee 

Update the permission for whole $OPT; you may again.

**Comment by wenminglu-bom** [comment]
@jintaglee 

99% tests passed, 1 tests failed out of 588

Subproject Time Summary:
fckit    =   2.18 sec*proc (13 tests)
gsw      =   0.41 sec*proc (2 tests)
ioda     =  14.83 sec*proc (15 tests)
oops     =  76.07 sec*proc (159 tests)
saber    = 216.82 sec*proc (144 tests)
ufo      = 337.53 sec*proc (138 tests)

Label Time Summary:
atlas            =  35.57 sec*proc (117 tests)
download_data    =  31.66 sec*proc (2 tests)
executable       = 116.77 sec*proc (216 tests)
fortran          =   4.45 sec*proc (34 tests)
mpi              = 153.43 sec*proc (103 tests)
openmp           = 161.20 sec*proc (118 tests)
script           = 534.98 sec*proc (370 tests)

Total Test time (real) = 685.48 sec

The following tests FAILED:
        284 - test_qg_4dvar_saddlepoint (Failed)
Errors while running CTest

**Comment by jintaglee** [comment]
@wenminglu-bom, I think that test failed because of floating-point roundoff error. I will have a look at it later but I think at this stage we can safely assume jedi-stack is now installed correctly.
